#!/usr/bin/env python3
"""
SGSI Infrastructure Generator
============================
Generates Terraform modules and infrastructure from YAML definitions.
"""

import os
import sys
import yaml
import json
import argparse
from pathlib import Path

def main():
    """Main generator function"""
    parser = argparse.ArgumentParser(description='SGSI Infrastructure Generator')
    parser.add_argument('--validate-only', action='store_true', 
                       help='Only validate YAML files, do not generate')
    parser.add_argument('--clean', action='store_true',
                       help='Clean generated directory before generation')
    
    args = parser.parse_args()
    
    print("🏗️ SGSI Infrastructure Generator")
    print("=" * 50)
    
    if args.clean:
        print("🧹 Cleaning generated directory...")
        clean_generated_directory()
        
    if args.validate_only:
        print("🔍 Validating YAML definitions...")
        validate_yaml_files()
        print("✅ All YAML files are valid")
        return
        
    print("🚀 Generating infrastructure...")
    generate_all_infrastructure()
    print("✅ Generation completed successfully")

def clean_generated_directory():
    """Clean the generated directory"""
    generated_dir = Path("generated")
    if generated_dir.exists():
        for file in generated_dir.rglob("*.tf"):
            file.unlink()
            print(f"Removed: {file}")

def validate_yaml_files():
    """Validate all YAML definition files"""
    definitions_dir = Path("definitions")
    
    if not definitions_dir.exists():
        print("⚠️ No definitions directory found")
        return
        
    yaml_files = list(definitions_dir.rglob("*.yaml")) + list(definitions_dir.rglob("*.yml"))
    
    for yaml_file in yaml_files:
        try:
            with open(yaml_file, 'r', encoding='utf-8') as f:
                yaml.safe_load(f)
            print(f"✅ {yaml_file}")
        except Exception as e:
            print(f"❌ {yaml_file}: {e}")
            sys.exit(1)

def generate_all_infrastructure():
    """Generate all infrastructure components"""
    
    # Create generated directory structure
    generated_dir = Path("generated")
    generated_dir.mkdir(exist_ok=True)
    
    # Generate basic Terraform configuration
    generate_terraform_config()
    generate_backend_config()
    
    print("✅ Infrastructure generation completed")

def generate_terraform_config():
    """Generate basic Terraform configuration"""
    terraform_content = '''# Auto-generated by SGSI Infrastructure Generator
terraform {
  required_version = ">= 1.0"
  
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = var.aws_region
  
  default_tags {
    tags = {
      Project         = "SGSI-Implementation"
      ManagedBy      = "Terraform"
      Generated      = timestamp()
      Environment    = var.environment
    }
  }
}

variable "aws_region" {
  description = "AWS region"
  type        = string
  default     = "us-east-1"
}

variable "environment" {
  description = "Environment name"
  type        = string
  default     = "development"
}
'''
    
    with open("generated/main.tf", "w") as f:
        f.write(terraform_content)
    
    print("📄 Generated main.tf")

def generate_backend_config():
    """Generate backend configuration"""
    backend_content = '''terraform {
  backend "s3" {
    bucket         = "terraform-state-bucket-051963532279"
    key            = "aws-iam-roles/terraform.tfstate"
    region         = "us-east-1"
    dynamodb_table = "terraform-locks"
    encrypt        = true
  }
}
'''
    
    with open("generated/backend.tf", "w") as f:
        f.write(backend_content)
    
    print("📄 Generated backend.tf")

if __name__ == "__main__":
    main()